### ISSUE TITLE
Sending alert from uptime kuma

### ISSUE THREAD

**Issue by iptvcld** [ncarlier/webhookd#100]
Hello; i am trying to send an alert from Kuma webhook using preset- multipart/form-data and i cannot just see the saw data coming into the webhook.  

Is there a method or script i should be using to see the raw data coming in from Kuma?

**Comment by ncarlier** [comment]
Hello, thanks for reporting the problem. Indeed, `multipart/form-data` is not that well supported. I will fix this asap. However you can use Kuma's webhook using `application/json` preset. The JSON payload will be stored into the `$1` variable.

**Comment by iptvcld** [comment]
> Hello, thanks for reporting the problem. Indeed, `multipart/form-data` is not that well supported. I will fix this asap. However you can use Kuma's webhook using `application/json` preset. The JSON payload will be stored into the `$1` variable.

Thanks I will try that. Is there a way to see the data come live on the screen?

**Comment by iptvcld** [comment]
> Hello, thanks for reporting the problem. Indeed, `multipart/form-data` is not that well supported. I will fix this asap. However you can use Kuma's webhook using `application/json` preset. The JSON payload will be stored into the `$1` variable.

I have to make a bash script to store $1 into a log file and then run the hook to view the file.  Is there something built in that i can use that shows the incoming data thats in $1?

**Comment by ncarlier** [comment]
You can echo the variable inside your script. Then retrieve hook logs or
enable hook log module: `WHD_LOG_MODULES=hook`.
