### ISSUE TITLE
Logs being generated for each webhook

### ISSUE THREAD

**Issue by iptvcld** [ncarlier/webhookd#102]
How can i stop the log file being made on each webhook - the file by default is going to /tmp and i have the -log-level set to error.  There are no errors being presented yet a new file is being made on each hit.

This folder can grow a whole lot if I leave it like that.

Thank you!

**Comment by ncarlier** [comment]
Curently, there is no option to disable hook's logs (mainly because of the notification system).
As an alternative you can create a cleanup cron job such as : `find /tmp -type f -mtime +2 -name '*.txt' -delete`
(or let's the /tmp directory being clear on each reboot.)

**Comment by iptvcld** [comment]
Thank you!
