### ISSUE TITLE
Parse more than one URL encoded variable

### ISSUE THREAD

**Issue by iluvatyr** [ncarlier/webhookd#108]
When I try to pass more than just one variable to the webhook, it does not work, as only the first variable is received.

Could someone tell me how to make something like:

```
#!/bin/sh

echo "Hello ${name}, do you want to ${command}?"
```

Work?

`curl localhost:8080/scriptname?name=Max&command=play` 

does not work unfortunately.

Thanks in advance

**Comment by ncarlier** [comment]
It should work... Here, your example works without a hitch:
![image](https://github.com/user-attachments/assets/e28ddb92-979b-42ed-aefe-aaccea1391f1)

Do you use quotation marks for the CURL URL?  Without quotation marks, '&' can be a problem for your Shell.

**Comment by iluvatyr** [comment]
Well, thanks for the info. Indeed, with quotations it works. I'm impressed with the fact that I did not think of such a basic thing. Wow.
