### ISSUE TITLE
Short Style server options seems broken

### ISSUE THREAD

**Issue by pouicr** [ncarlier/webhookd#12]
Hi,

Short style option seems broken (and incoherent with "usage" display):

This is failing:
```bash
/usr/local/bin/webhookd -l :8080 --scripts /etc/webhook -t 120 
```

while this OK
```bash
/usr/local/bin/webhookd --listen :8080 --scripts /etc/webhook --timeout 120 
``` 

Usage display:
```
Dec 19 17:56:07 jungle webhookd[4698]: Password file (encoded with htpasswd) (default ".htpasswd")
Dec 19 17:56:07 jungle webhookd[4698]: -scripts string
Dec 19 17:56:07 jungle webhookd[4698]: Scripts directory (default "scripts")
Dec 19 17:56:07 jungle webhookd[4698]: -timeout int
Dec 19 17:56:07 jungle webhookd[4698]: Hook maximum delay before timeout (in second) (default 10)
Dec 19 17:56:07 jungle webhookd[4698]: -version
Dec 19 17:56:07 jungle webhookd[4698]: Print version
```

No shorten options displayed, one "-" or two?

**Comment by ncarlier** [comment]
Not all arguments are shortened. Timeout for instance is not.
CLIs use the standard [Go flag package](https://golang.org/pkg/flag/) which is not POSIX. And in this case, there is no difference with one or two dashes. "-timeout" is equal to "--timeout"
I should use a POSIX command line analyzer but I try to keep this tool small and simple by using almost zero external dependencies.

**Comment by pouicr** [comment]
Ok, I cannot find any -t option. Even if it not fully consistent, nothing is wrong.
