### ISSUE TITLE
Script not found

### ISSUE THREAD

**Issue by lokingwei** [ncarlier/webhookd#16]
First, thank you for this wonderful package, it's exactly what I need.

However, followed your readme file, setup webhookd as docker container.
It reply me Script not found: scripts/test.sh.

command used:
`docker run --rm --name=webhookd -v ~/webhookd:/var/opt/webhookd/scripts -p 8080:8080 ncarlier/webhookd`

This is the directory structure inside the container:
```
bash-4.4# pwd
/var/opt/webhookd/script
bash-4.4# ls -al
total 12
drwxr-xr-x    2 1000     1000          4096 Dec 31 07:52 .
drwxr-xr-x    5 root     root          4096 Dec 30 21:45 ..
-rwxrwxrwx    1 1000     1000            19 Dec 31 08:02 test.sh
bash-4.4#
```

Below is the content of my test.sh:
```
#!/bin/bash
ps aux
```

This is the result of the post request:
```
ERROR: 2018/12/31 08:10:21 index.go:61: Script not found: scripts/test.sh
INFO: 2018/12/31 08:10:21 logger.go:25: 1546243821109422472 POST /test 192.168.33.1:57640 PostmanRuntime/7.4.0 54.439µs
```

**Comment by ncarlier** [comment]
Hi,

ok I see the pb. I deleted the `env` file from the Docker example. As a result, the example became incorrect. Sorry! I will fix that.

By default, the daemon searches for scripts in the `./scripts' directory. You can change this location using the command parameter `--scripts` or the env variable `APP_SCRIPTS_DIR`.

For your example, you just have to add this last variable env:

```bash
docker run --rm --name=webhookd -v ~/webhookd:/var/opt/webhookd/scripts -p 8080:8080 -e APP_SCRIPTS_DIR=/var/opt/webhookd/scripts ncarlier/webhookd
```

or using the command line parameter:

```bash
docker run --rm --name=webhookd -v ~/webhookd:/var/opt/webhookd/scripts -p 8080:8080 ncarlier/webhookd webhookd --script=/var/opt/webhookd/scripts
```

**Comment by lokingwei** [comment]
Thank you for your answering.
Another question, is it possible to stream output for the script that runs for a long duration?
