### ISSUE TITLE
Support CORS header?

### ISSUE THREAD

**Issue by lokingwei** [ncarlier/webhookd#17]
I getting cors error when calling the API from remote FE client.

Is there any way to add support for the cross-origin request?

**Comment by ncarlier** [comment]
Hi,

Webhookd is, for the moment, not designed to be used as a web front end. A few elements are still missing. Such as SSL, CORS, etc. IMHO you should place in front of it, a reverse proxy or an API gateway (ex: [NGINX](https://nginx.org), [Traefik](https://traefik.io/), [Kong](https://konghq.com/kong/), [Envoy](https://www.envoyproxy.io/), ...). This will allow you to properly protect and monitor the API (SSL, Rate Limiting, AuthN, Metrics, etc.).

However, I will probably add basic CORS support (Access-Control-Allow-Origin: *) in the next version.

**Comment by ncarlier** [comment]
Hi, CORS is now supported by the release 1.5.1.

regards
