### ISSUE TITLE
provide option to log script output to stdout

### ISSUE THREAD

**Issue by stefanfoulis** [ncarlier/webhookd#2]
Having all the output (including the webhook scripts) in the console/log would make debugging easier.

**Comment by ncarlier** [comment]
It seems to be a good idea but only for debugging purpose. The script output can be huge depending what is done. Concurrent script executions can also make the log output  tricky to read. I will work on that. Thx

**Comment by ncarlier** [comment]
Done. Set APP_SCRIPTS_DEBUG=true to redirect the script output in the console.
