### ISSUE TITLE
Binary download method not working

### ISSUE THREAD

**Issue by M1T0zd** [ncarlier/webhookd#21]
Using the command `sudo curl https://raw.githubusercontent.com/ncarlier/webhookd/master/install.sh | bash` gives an error eventually:

> Downloading https://github.com/ncarlier/webhookd/releases/download/v1.6.1/webhookd-linux-armv6l.tgz to /tmp/webhookd-linux-armv6l.tgz ...

> curl: (22) The requested URL returned error: 404 Not Found
> error: Unable to download binary for your architecture.

The page isn't there. Is this just something on my end?

**Comment by ncarlier** [comment]
Hello, the script is a very (too) simple helper to automate downloading of pre-built binaries. You can find all pre-built binaries here: https://github.com/ncarlier/webhookd/releases/tag/v1.6.1

For your Raspberry, the best option is maybe to build and install the binary using `go get`. Or maybe try to manualy get the ARM binary (not tested on RPI): https://github.com/ncarlier/webhookd/releases/download/v1.6.1/webhookd-linux-arm.tgz

**Comment by M1T0zd** [comment]
Alright, thanks.
My knowledge on binaries isn't too great, but I'll give it a try.

I love the idea by the way. Very cool!
