### ISSUE TITLE
Authentification with github

### ISSUE THREAD

**Issue by azlux** [ncarlier/webhookd#23]
Hi,
I try to use this project with github. It's really easy, simple and useful.
I want to add authentication but it's look like github don't use authentication but pass the secret into json message.
I suppose you don't manage it ?
I think I need a script to manage the secret ? (with `jq` for example)
Any suggestion ?

Best regards
Azlux

**Comment by ncarlier** [comment]
Hi,

Your understanding is correct. `jq` is a perfect fit to extract a secret from a JSON message.
Regarding GitHub webhooks: [headers](https://developer.github.com/webhooks/#delivery-headers) contains this header: `X-Hub-Signature`. All headers are translated into shell variable.
Therefore, you can access this signature using the `x_hub_signature` variable and finally validate it with the secret.

regards

**Comment by azlux** [comment]
Here the code I will use :
```
#!/usr/bin/env bash
password="********"
res=$(echo -n $1 | openssl sha1 -hmac "$pasword")
script_to_run=('/pat/to/my/script')

[ "$x_hub_signature" == "$res" ] && echo "${script_to_run[@]}" || echo ""
```
Can we good to add some examples like that somewhere
Azlux

**Comment by ncarlier** [comment]
Feel free to propose a pull request with examples in the script directory.
A `scripts/github_example.sh` would be great.

Here another "real life" example: https://gist.github.com/ncarlier/a2a9eef7e819ef99a006b5e5b4c607d1

**Comment by azlux** [comment]
Can you add yours ? Or I can do it.

**Comment by ncarlier** [comment]
I can add this Github example and I think I can also share a Docker Swarm deployment script.
But if you have a "real-life" example that you think would be useful to someone else, feel free to submit a PR.

**Comment by ncarlier** [comment]
Examples added: https://github.com/ncarlier/webhookd/tree/master/scripts/examples
