### ISSUE TITLE
[FR] Proposal

### ISSUE THREAD

**Issue by azlux** [ncarlier/webhookd#24]
Bonjour,
J'apprécie beaucoup ce projet. Simple et efficace. 

Je dispose de mon propre repo apt : https://packages.azlux.fr/
Il est possible  pour moi d’intégrer tout type de projet.
Je vais ajouter celui-ci à ma liste, car je pense fortement qu'il en vaut le coup.
Un fois de .deb fait, tout est automatisé de mon coté. Ce qui permet de donner aux utilisateurs un moyen de d'install et de mise à jour automatisé avec APT.

Qu'en pensez-vous ?
Azlux

**Comment by ncarlier** [comment]
C'est une super idée!
J'aimerai bien à terme avoir un package officiel Debian mais j'ai aucune idée de la marche à suivre.

**Comment by azlux** [comment]
Des retours que j'ai eu, c'est assez compliqué.
Plein de contraintes et il faut être bien vu par les contributeurs Debian. Y a quand même une grosse confiance à donner. Pas mal de choses sont quand même vérifié sur ton code et tes modif release par release.

De mon coté je te fait ça dès que possible. J'aurais 2-3 question à te poser quand à l'install. Serais-il possible de se parler [à vive voix](https://mumble.azlux.fr) un soir ? (Optionnel, et Mumble n'est qu'une option)

**Comment by ncarlier** [comment]
Avec plaisir.

**Comment by azlux** [comment]
Je viens de mettre le projet sur mon repo. Tu peux tester si tu veux.
Mais si il faut faire un service (de type systemd), il va falloir en discuter car il y a qq limitations.
Tu peux passer par mon mail qui est sur mon profil pour éviter les discussion sur le ticket.

**Comment by ncarlier** [comment]
MP sent
