### ISSUE TITLE
Services Shutdown after many days

### ISSUE THREAD

**Issue by azlux** [ncarlier/webhookd#27]
After many days running (14days last time) the service stop without error.
I can see the service get down, without error :
```
Mar 26 17:55:21 packages systemd[1]: Stopping WEBHOOKD...
Mar 26 17:55:22 packages systemd[1]: webhookd.service: Succeeded.
Mar 26 17:55:22 packages systemd[1]: Stopped WEBHOOKD.
```

Strange thing, the service should restart https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart= with `Restart=always`

**Comment by ncarlier** [comment]
According to the log, everything is OK and it's a graceful shutdown. The graceful shutdown can only be triggered by a SIGINT or SIGTERM. With systemd, when you correctly stop a service, the restart will not be triggered. Looks like something sent a stop signal to the department.
