### ISSUE TITLE
Which Path of the scripts ?

### ISSUE THREAD

**Issue by jonny6015** [ncarlier/webhookd#29]
I can't find the scripts folder .... could you tell me where is it ?
i install webhooks use APT.

**Comment by ncarlier** [comment]
Hi,

You can edit `/etc/default/webhookd.env` or `/etc/webhookd.env` file and specify where your scripts are. Ex: `WHD_SCRIPTS="/opt/scripts"` 

See: https://github.com/ncarlier/webhookd/blob/master/etc/default/webhookd.env#L29

PS to @azlux: Maybe you should set by default a script location. Something like `/var/lib/webhookd` or equivalent.

**Comment by azlux** [comment]
https://github.com/azlux/dpkg-deb/blob/master/webhookd/webhookd.service#L8-L9

You prefer me creating the `/etc/webhookd.env` file with this option inside or maybe remove the comment on WHD_SCRIPTS into the default config ?

**Comment by ncarlier** [comment]
IMHO use a custom value inside the /etc/webhookd.env that respect Debian conventions could be a good option. That would concerns only the script directory. It should also be created by APT. What do you think?

**Comment by jonny6015** [comment]
this issues can closed,thanks very much

**Comment by azlux** [comment]
done. It's will be effective on next release.
