### ISSUE TITLE
Request We couldn’t deliver this payload: Service Timeout

### ISSUE THREAD

**Issue by jonny6015** [ncarlier/webhookd#30]
then I had a new problem , I use github to post a request , then i got “ Request
We couldn’t deliver this payload: Service Timeout” , I try to set the WHD_HOOK_TIMEOUT ，then it don't work , i still got the msg ... is the shell script execution time too long ? how can i fix it .....

![41CE0989-24EA-450E-8C10-E186EC53CD2D](https://user-images.githubusercontent.com/58116035/80467189-1337fc00-8970-11ea-8c00-5f0bd4905f65.jpeg)

**Comment by ncarlier** [comment]
You have to isolate the pb.

- First try to manually deliver this payload to the webhook:
```
curl --data @payload.json http://localhost:8080/github_hook
```
- Use a simple `echo` script to ensure that your script is not the reason of the timeout.

**Comment by jonny6015** [comment]
simple script can work . eg: echo script or some simple script . now , my script contains npm command , may be it will take longer,

**Comment by jonny6015** [comment]
> You have to isolate the pb.
> 
> 
> 
> - First try to manually deliver this payload to the webhook:
> 
> ```
> 
> curl --data @payload.json http://localhost:8080/github_hook
> 
> ```
> 
> - Use a simple `echo` script to ensure that your script is not the reason of the timeout.

i use `curl --data @payload.json http://localhost:8080/github_hook` to try find error , checked step by step and found that when executing "npm install " ,got an error was reported:   `  error: signal: killed   `

**Comment by ncarlier** [comment]
`npm install` is maybe the heaviest command on earth ;)

You have several options:
- Increase WHD_HOOK_TIMEOUT
- Pre-install node dependencies in order to reduce npm time
- Fork npm stuff in a sub process in order to do the task in background (be careful to add a bit of logic to avoid the mass creation of processes if the hook is often called)

**Comment by ncarlier** [comment]
According to [GithHub documentation](ttps://developer.github.com/v3/guides/best-practices-for-integrators/#favor-asynchronous-work-over-synchronous) you can't exceed 10 seconds. Therefore npm cache or background task are the best options.

**Comment by jonny6015** [comment]
yeah ,thanks , I try to new an other .sh script , it's ok , then I try to remove 'npm install '  , make it fast
