### ISSUE TITLE
Reverse proxy

### ISSUE THREAD

**Issue by EmilMoe** [ncarlier/webhookd#31]
I'm trying to make this work through a reverse proxy (I'm using Docker), but I keep getting this error:

```
INF 2020/06/01 22:01:42.976802 server is ready to handle requests at :443

ERR 2020/06/01 22:01:42.977083 could not listen on :443 : open server.pem: no such file or directory
```

Anyone got an  idea what to do?

**Comment by ncarlier** [comment]
Hi,

as soon you use `--tls-listen-addr=443` webhookd is expecting a certificate file: https://github.com/ncarlier/webhookd#tls
If you are behind a reverse proxy you can delegate TLS to your reverse proxy and use an classic HTTP port (`--listen-addr=8080`).

**Comment by EmilMoe** [comment]
> Hi,
> 
> as soon as you use `--tls-listen-addr=443` webhookd is expecting a certificate file: https://github.com/ncarlier/webhookd#tls
> If you are behind a reverse proxy you can delegate TLS to your reverse proxy and use an classic HTTP port (`--listen-addr=8080`).

Perfect thanks :)
