### ISSUE TITLE
Problem with characters and Gitlab

### ISSUE THREAD

**Issue by EmilMoe** [ncarlier/webhookd#32]
I'm using the example script from here, anyone got a solution to it? I think it's related to `jq` though.

```
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 2, column 1
error: bad body format: expecting JSON
error: exit status 1
```

**Comment by ncarlier** [comment]
Hi,
You're right. It appears JSON's payload is incorrect. JSON object is checked here: https://github.com/ncarlier/webhookd/blob/master/scripts/examples/gitlab.sh#L19
You can add a debug statement before this line to understand what's going on: 

```bash
...
[ -z "$payload" ] && die "missing request payload"
debug "received payload: $payload"
payload_type=$(echo $payload | jq type -r)
...
```

(NB: Add `debug=true` query parameter to activate script debug function)

**Comment by EmilMoe** [comment]
Seems the issue is here, I wonder how it could happen

```
	"commits": [{
				"id": "1665874f2138b5ecd60902302eff4da7ee",
				"message": "Bugfix
                                 ","
```

**Comment by EmilMoe** [comment]
Adding this, fixed the error:

```
payload=$1
payload="$(echo "$payload"|tr -d '\n')"
```
