### ISSUE TITLE
Timeout env var

### ISSUE THREAD

**Issue by 1300371** [ncarlier/webhookd#37]
According the documentation, we should use `WHD_HOOK_TIMEOUT` but in the _usages_ of `webhookd`, it says: `WHD_TIMEOUT`.

And finally, it works only with `WHD_TIMEOUT`.

Btw, great project !!

**Comment by ncarlier** [comment]
Thx for the report!

**Comment by MhdSyrwan** [comment]
Thanks for the fix!

When this bugfix is going to be in production (pushed as docker image)?

**Comment by ncarlier** [comment]
Hello, latest Docker image was ok but not tagged. So I just release the v1.11 in order to also include SMTP improvements. Thanks.
