### ISSUE TITLE
I get error in curl `transfer closed with outstanding read data remaining`

### ISSUE THREAD

**Issue by Tibingeo** [ncarlier/webhookd#4]
```
data: Hook work request "test" queued...

data: Run sample test

curl: (18) transfer closed with outstanding read data remaining
```
script_runner.go:98: scripts/test.sh executed wit SUCCESS

I have set APP_HOOK_TIMEOUT="300" and it is getting executed successfully, but curl response is failing.

**Comment by ncarlier** [comment]
Hello,

can you share the script content?
According to cURL [documentation](https://curl.haxx.se/libcurl/c/libcurl-errors.html) error code 18 refers to:

> A file transfer was shorter or larger than expected. This happens when the server first reports an expected transfer size, and then delivers data that doesn't match the previously given size.

This might mean that the script contains an asynchronous process. The script is finished but stdout keeps writing something.

**Comment by Tibingeo** [comment]
I was running a sample script to test timeout feature, my script just have 
```
sleep 15
echo "Completed"
```

**Comment by Tibingeo** [comment]
Also tried with another script 
```#!/bin/bash
for i in {1..15}
do
    sleep 1
    echo `date +%s`
done
```
**OUTPUT**
```
data: Hook work request "run_behave" queued...
data: 1521639175
data: 1521639176
data: 1521639177
data: 1521639178
data: 1521639179
data: 1521639180
data: 1521639181
data: 1521639182
data: 1521639183
curl: (18) transfer closed with outstanding read data remaining
```

Failed after 10 seconds 
tried passing `-H "X-Hook-Timeout: 15"` also did not work.

**Comment by ncarlier** [comment]
I've spotted the problem. The HTTP server has an overall timeout of 10 seconds.
I just fixed that and pushed a new release: 1.2.2

Thanks a lot!

**Comment by Tibingeo** [comment]
Thank You @ncarlier for fixing this issue.

**Comment by Tibingeo** [comment]
Now is HTTP server timeout is configurable ?

**Comment by ncarlier** [comment]
Not currently. It's configured indirectly with the hook's timeout (at least for the server writing timeout). 
Maybe in a next release I will set a configurable maximum limit.
