### ISSUE TITLE
How to echo strings in docker logs contexts

### ISSUE THREAD

**Issue by comicsheep** [ncarlier/webhookd#44]
Hi @ncarlier 
Thank you for this gorgues utility.
In my case, can scripts called by webhookd print result strings in docker logs contexts?
e.g.
#!/bin/bash
echo 111
then I can see 111 in "docker logs webhookd"

**Comment by ncarlier** [comment]
Now, you can use `-hook-log-output` or `WHD_HOOK_LOG_OUTPUT=true` to redirect hook execution logs to server logs.
