### ISSUE TITLE
Add config variable for changing '/static' path for serving static HTML files to different name

### ISSUE THREAD

**Issue by simoniz0r** [ncarlier/webhookd#45]
I was wondering if it would be possible for you to add a config variable to change the `/static` path to something different.  For example, I'd like to change it to `/docs` as a more intuitive way to provide documentation on the endpoints I've made using webhookd.

Thanks for making such an awesome and easy to use tool!

**Comment by ncarlier** [comment]
Hi, it seems like a good idea to me. Thanks for the proposal.

**Comment by ncarlier** [comment]
You can use `--static-path` to specify the path.
