### ISSUE TITLE
Ability to execute Lua (Shell) scripts ?

### ISSUE THREAD

**Issue by nodecentral** [ncarlier/webhookd#47]
Hi

Looking at the build/dockerfile - I have a number of Lua scripts that I’d like to execute from the bash/shell/command line. 

Here’s an example `lua_test.lua` to run.
````
#!/usr/bin/lua

print ("Hello World!")
print ("*******************")
local saydatetime = os.date('%H, %M. On. %A %B %d :')
print(saydatetime)
print ("*******************")

````

What would I need to do to enable that capability ?

**Comment by ncarlier** [comment]
Hi,

if you are using Docker you have to create your own `Dockerfile` and install lua interpreter (`RUN apk install lua5.3`).
Don't forget to make your script executable (`chmod +x lua_test.lua`).
