### ISSUE TITLE
my nfs server can't found the script

### ISSUE THREAD

**Issue by JovanyNegocio** [ncarlier/webhookd#48]
Hi
When I execute:
curl -v -XPOST http://localhost:8080/foo/bar
I receive this error:
ERR 2021/08/12 13:49:06.514247 Script not found: scripts/foo/bar

**Comment by ncarlier** [comment]
Can you share your configuration? Scripts directory location is certainly not properly set. By default, the daemon searches for scripts in the `./scripts` directory. You can change this location using the command parameter `--scripts` or the env variable `WHD_SCRIPTS`.

**Comment by JovanyNegocio** [comment]
@ncarlier thank you so much for your time.
flow my scripts configuration:

[root@server-test scripts]# pwd
/root/scripts
[root@server-test scripts]# tree
.
└── foo
    └── bar.sh

1 directory, 1 file
[root@server-test scripts]# 

Ps: I'm using centos

**Comment by ncarlier** [comment]
How do you start webhookd? 
You should start webhookd like this:

```bash
webhookd --scripts /root/scripts`
```

or like this:

```bash
export WHD_SCRIPTS=/root/scripts
webhookd
```

or if your current dir is `/root`:

```bash
pwd
# /root
webhookd
```

Make sure that `bar.sh` is executable: `chmod +x bar.sh`.

PS: please consider using another user than root to run webhookd. It is risky in terms of security (unless you are perfectly chrooted or sandboxed).
