### ISSUE TITLE
Script not found

### ISSUE THREAD

**Issue by marcin-jedynski** [ncarlier/webhookd#5]
Hey, I'm using image from hub.docker.com and I encountered a problem with "Script not found"  message when I try to do your example foo/bar.
Regardless of specified value of APP_SCRIPTS_DIR in docker-compose file still i get message "Script not found".

**Comment by ncarlier** [comment]
The `foo/bar` script is only an example and does not exist in the `scripts` folder of this repository. You must create it in the mounted folder. For a quick test, you can try the test script: `curl -XPOST localhost:8080/test`

However I found another pb in the Docker image (maybe related to yours in fact). The bash shell is missing. So `#!/bin/bash` scripts do not run. I just corrected. Can you pull the image again?

**Comment by ncarlier** [comment]
Any update?
