### ISSUE TITLE
Pass header  in response

### ISSUE THREAD

**Issue by icodus** [ncarlier/webhookd#56]
Not an issue, thanks for the great code!
But, would that be possible to pass a header from the executed script?
Something like:
echo header: "X-Auth-Token $token"

**Comment by ncarlier** [comment]
Hi, thank you!
I am sorry but this is not possible because of the use of streaming. The script execution is streamed and headers already sent.

**Comment by icodus** [comment]
That's what I thought, telling true :-) Closing.
