### ISSUE TITLE
Log public ip address behind reverse proxy

### ISSUE THREAD

**Issue by helmut72** [ncarlier/webhookd#59]
Would be cool to log X-Forwarded-For header in your logs instead of reverse proxy ip address. Thank you.

**Comment by ncarlier** [comment]
Good point. I will fix that.

**Comment by helmut72** [comment]
I have compiled webhookd with your commit from yesterday:
https://github.com/ncarlier/webhookd/commit/50bcb16c715c50860d8114c7893419c71eb17ae9

Works. Thank you very much!

Btw, really a fantastic tool! I'm used to use bash scripts nearly everywhere because I don't need performance from a binary most of the time.
Starting my scripts with a webhook gives me so many possibilities I can't imagine now. For example using it from my mobile phone.

**Comment by helmut72** [comment]
When do you release a `:latest` version on Dockerhub with this feature included? Your `:edge*` images on Dockerhub looks like are not meant to include other packages with `apk`.

Only asking because I just found my build on my harddrive. Thank you.

**Comment by ncarlier** [comment]
It's done.

**Comment by helmut72** [comment]
Thank you! 👍
