### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by eternal-flame-AD** [ncarlier/webhookd#6]
I think it would be much more convenient if we can add authentication like HTTP Authentication, query parameter,IP restriction etc.

**Comment by ncarlier** [comment]
That's right. But generally for all AuthN concerns, I usually rely on a third-party service with a high level of security and configuration. For example, I use webhookd in production behind an API gateway called [Kong](https://konghq.com/). You can put all the restrictions you want and plug in almost all AuthN and AuthZ mechanisms.

However, I will see if I can find time to add a very simple authentication feature (Basic Auth or API key).

Besides, you can do a lot of things into the shell script! Validating an API key is simple and validating a Basic Auth header should not be more difficult ;)

**Comment by eternal-flame-AD** [comment]
I think auth methods should live as HTTP middlewares living in an auth package. I could submit a PR if you want :)

**Comment by ncarlier** [comment]
You are truly welcome! :smile:
