### ISSUE TITLE
Override mailto in WHD_NOTIFICATION_URI

### ISSUE THREAD

**Issue by helmut72** [ncarlier/webhookd#60]
Would be cool to override `mailto:foo@bar.com` parameter in WHD_NOTIFICATION_URI, when a script prefix also contains a mail address, for example:

```
echo "notify:foo2@bar.com: Hello World"
```

or:
```
echo "notify:foo2@bar.com,foo3@bar.com,foo4@bar.com: Hello World"
```

If there is no mail address after the prefix, default address will be used.

Same should be possible with HTTP post hook notifications:

```
echo "notify:http://requestb.in/another987: Hello World"
```

Thank you.

**Comment by helmut72** [comment]
I sleep some nights and maybe this feature request is not much important. I can also send mails in my script with msmtp or messages with curl. Also any combinations are possibles. Will close this issue. You can re-open it if it's important for you.

**Comment by ncarlier** [comment]
You are right, sleep is a precious friend ;) The purpose of the notification is more to trigger other actions after success or error.
