### ISSUE TITLE
Add prefix to htpasswd for special paths

### ISSUE THREAD

**Issue by helmut72** [ncarlier/webhookd#61]
Would be cool to add a prefix to htpasswd file to use different users for different paths. For example:

```
/services1:api1:abcdef654321 # will be used for all scripts in /services1, eg. /services1/foo
/services2:api2:abcdef123456 # will be used for all scripts in /services2, eg. /services2/bar
/:api:default000000 # will be used for all other paths or scripts in the root path, eg. /other/foo or /bar
```

Thank you.

**Comment by ncarlier** [comment]
It's an idea. I'm wondering if putting htpasswd file at different location is another solution...

**Comment by helmut72** [comment]
Yes, that would be also ok. If `/scripts/services1/htpasswd` exists, this one is used instead of the one in `WHD_PASSWD_FILE`.

Another idea is a comma separated list in the variable:
```
WHD_PASSWD_FILE=/etc/webhookd/users.htpasswd,/etc/webhookd/services1.htpasswd,/etc/webhookd/services2.htpasswd,...
```

The first one is like now, any other entry will be used for folder names that matches without `.htpasswd`.

**Comment by helmut72** [comment]
I'm also close this issue. I think it's a easier to check different sources with different keys in the header. If I really want some basic auth, I put this to the reverse proxy. Let's keep webhookd small and simple.

If you think it's still an issue, please reopen it.
