### ISSUE TITLE
Can't extend 1.15.1 image with own packages

### ISSUE THREAD

**Issue by helmut72** [ncarlier/webhookd#64]
I just wanted to create my own image with additional apk packages from `:1.15.1`, but the problem is that you set in 1.15.1 `ARG USER=webhookd` and `ARG UID=1000`. Now `apk install ...` doesn't work.

1.15.0 works because there are no ARG USER and UID variables.

**Comment by ncarlier** [comment]
You must restore the root user while using the apk :

```Dockerfile
FROM ncarlier/wenbhooks:1.15.1

# use root in order to install packages
USER root

# install packages
RUN apk add --no-cache curl ...

# restore webhookd user
USER $USER
```

**Comment by helmut72** [comment]
I had a typo. Not my best days this weekend. Thank you!
