### ISSUE TITLE
Feature Request: Client Certificate authentification

### ISSUE THREAD

**Issue by smox** [ncarlier/webhookd#69]
Hello,

First of all, thank you for your work.
I want to use your webhookd for machine to machine communication and therefore I thought it would be awesome if you can implement a client certificate authentification or something similiar.

I know that you've already implemented .htaccess authentification but client certificates (or similiar things like ssh key authentification) would be much easier to deploy in an automated manner.

**Comment by ncarlier** [comment]
Thanks for your interest.
You can perform strong client authentication using [HTTP Signature](https://github.com/ncarlier/webhookd#signature).
However, it is "fairly new" and is not natively supported by common HTTP clients. For example, you need to install a plugin for HTTPie : https://pypi.org/project/httpie-signature/

**Comment by smox** [comment]
Thank you for your quick answer. It seems to be that this is exactly what I am searching for but I've never heard of that before. 
Thank you and best regards to france 👍
