### ISSUE TITLE
RPMs for openSUSE

### ISSUE THREAD

**Issue by smox** [ncarlier/webhookd#70]
Hello,

I use webhookd on openSUSE (latest leap and tumbleweed). For that I've build a rpm for easier deployment on my machine.
I you are interested, I can contribute this packages or an automated build process (e.g OpenBuildService).

What your thoughts about that?

**Comment by ncarlier** [comment]
I think that would be great!

**Comment by smox** [comment]
Hello! I am sorry that it takes so long but I have a 2 month old daughter at home and didn't have much time at the moment.
Currently I am gathering feedback because I want that it comply with the openSUSE Packaging Guidelines. This is the first package I want to publish. 

You can look at it here: https://build.opensuse.org/package/show/home:sm0x/webhookd 

I hope you like it and find it useful. 
If you have questions or you want some changes please feel free to ask.

**Comment by smox** [comment]
I am finish. 
You can install it using this page: https://software.opensuse.org/download.html?project=home%3Asm0x&package=webhookd

If you have any feedback, please let me know!

**Comment by ncarlier** [comment]
Hi Michael, please don't excuse yourself! Your contribution is valuable and parenting is much more important :)
I need to run a VM to test the packaging (my Linux distributions are generally under Debian or Ubuntu). But from the outside it looks great. Anyway, thanks a lot for the work. If you think it's ok I can add it to the installation methods in the documentation.

**Comment by smox** [comment]
What do you think about this [WIKI Page](https://en.opensuse.org/Webhookd)? 
Are you okay with it if I document it also in the openSUSE WIKI to point out some special things? For example the location of my scripts folder is not really intuitive for newcomers (it is the home folder for system users created by systemd).

**Comment by ncarlier** [comment]
It's great! Regarding the feature list, maybe something like this is more explicit:

- Trigger a shell script or executable via HTTP requests
- Passing the HTTP request parameters to the environment context of the script
- Live stream of the execution output 
- Send notification after the execution (email or HTTP request)
- Check the request integrity with HTTP Signature methods
- Authenticate the request with Basic Auth and TLS

**Comment by smox** [comment]
Much better! I've updated the WIKI and my Home Repository! :)
