### ISSUE TITLE
Do we have a variable for the IP address, just like $user_agent?

### ISSUE THREAD

**Issue by kodbuzz** [ncarlier/webhookd#73]
It would be super useful to have it as a variable in certain situations.

**Comment by ncarlier** [comment]
I just added [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) for identifying the originating IP address of a client. You can use the `x_forwarded_for` variable in your script.

**Comment by kodbuzz** [comment]
> I just added [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) for identifying the originating IP address of a client. You can use the `x_forwarded_for` variable in your script.

I made the mistake of trying it all in caps and it didn't work. 

I should have known that. Thanks for all your hard work and have a great new year!
