### ISSUE TITLE
Replace "docker-compose" with "docker compose" plugin

### ISSUE THREAD

**Issue by bluepuma77** [ncarlier/webhookd#81]
The [Dockerfile](https://github.com/ncarlier/webhookd/blob/master/Dockerfile) shows that docker-compose is installed:
```
# Install docker-compose
RUN curl -L --fail https://raw.githubusercontent.com/linuxserver/docker-docker-compose/master/run.sh \
     -o /usr/local/bin/docker-compose && \
     chmod +x /usr/local/bin/docker-compose
```
From [Docker Compose overview](https://docs.docker.com/compose/):
> From the end of June 2023 Compose V1 won’t be supported anymore
> Make sure you switch to [Compose V2](https://docs.docker.com/compose/compose-file/) with the `docker compose` CLI plugin

[Install the Compose plugin](https://docs.docker.com/compose/install/linux/):
```
$ sudo apt-get install docker-compose-plugin
```

Not sure how it would work with alpine.

PS: The text on [Docker Hub](https://hub.docker.com/r/ncarlier/webhookd/) seems outdated, it mentions `docker:dind`, which is not mentioned on the [Github page](https://github.com/ncarlier/webhookd).

**Comment by ncarlier** [comment]
Thank you very much for the report.
