### ISSUE TITLE
Error "openssl: not found" with /scripts/examples/github.sh in official Docker container

### ISSUE THREAD

**Issue by bluepuma77** [ncarlier/webhookd#82]
When trying to run [/scripts/examples/github.sh](https://github.com/ncarlier/webhookd/blob/master/scripts/examples/github.sh) in the [official Docker container](https://hub.docker.com/r/ncarlier/webhookd), I get the error "openssl: not found", followed by "error: bad hook signature". I tested with both `latest` and `edge-distrib`.

**Comment by ncarlier** [comment]
Thanks for the report. I added OpenSSL to the distribution image (`edge-distrib` ).
