### ISSUE TITLE
update ncarlier/webhookd:latest to 1.17.3

### ISSUE THREAD

**Issue by helmut72** [ncarlier/webhookd#85]
I'm used that `:lastest` is always the current release version and something like `:edge` is ongoing development. In Dockerhub your `:latest` is some months old (about 1.16.0), but your latest release is 1.17.3.

If you think about release v2 with non-compatible configurations to v1, also tagging `ncarlier/webhookd:1` would be great to have the latest release of v1. This avoid breaks when auto-updating with for example Watchtower.

Thank you.

**Comment by ncarlier** [comment]
Yes, I had a bit of trouble with automatic semantic releases. In the end, it's not a good idea and I'm going back to a manual publishing cycle. Docker publication was impacted and explain why the 1.17 is missing. Next release will be OK.
So far, there have been no real breaking change regarding new releases. At least nothing that would interfere with the program's behavior.
That said, you're right about the need for publishing a release with the major number. I have to figure out how to do it.

**Comment by raiyni** [comment]
Kind of necro'ing this but you can achieve what's said in the OP easier by splitting edge and the latest/tag into two different CI actions.

**Comment by ncarlier** [comment]
`ncarlier/webhookd:1` Docker image is live.

**Comment by helmut72** [comment]
Thanks!
