### ISSUE TITLE
[Feature Request]: ssh support

### ISSUE THREAD

**Issue by pucherot** [ncarlier/webhookd#86]
I think it would be a good solution to add `ssh` support to the image. In this way, scripts can invoked host commands, command in other containers or command in other servers.

It's only necessary to add the following command to the Dockerfile file. (or merge this command with another `apt` command already existing at line 84 of Dockerfile.

```
RUN apk add --no-cache --purge openssh
```

Additionally, users can share a ssh path to configure the container ssh key:
```
    volumes:
      - ./scripts:/scripts
      - ./ssh:/.ssh
```

**Comment by ncarlier** [comment]
Hi, OpenSSH is already part of the "distribution" image:
```bash
docker pull ncarlier/webhookd:latest-distrib
```

**Comment by pucherot** [comment]
Fantastic, I had forgotten that there is a more complete image with additional command like ssh.

Thank you so much.
