### ISSUE TITLE
[Feature Request] dynamically add packages

### ISSUE THREAD

**Issue by Nionor** [ncarlier/webhookd#91]
I know I can use the -distrib to get most useful tools but maybe you could add an environment variable for additional packages to the slim version (or both) so we can add our own if we just need some specific ones.

I usually just use the slim one and install the packages I want once it up and running to keep it small, but this would be nice. 😃

**Comment by ncarlier** [comment]
Hi, the docker entry point could handle this, but it would require running the container as root, which would be a security issue.
However, for this need, I prefer to handle it simply with webook scripts. With a special init script ("setup.sh") or directly in the script that requires the dependency.

Here's an example I used to install the Minio client.

```bash
if ! command -v mc &> /dev/null
then
  echo "installing mc..."
  wget https://dl.min.io/client/mc/release/linux-amd64/mc -P /usr/local/bin
  chmod +x /usr/local/bin/mc
fi
```

**Comment by Nionor** [comment]
Ah true, that is a nice solution, thanks for the idea!
