### ISSUE TITLE
version tags for lightweight docker image

### ISSUE THREAD

**Issue by r3mi** [ncarlier/webhookd#94]
Hello,
thanks for this tool !
Is it possible to have version tags for the lightweight docker image ?
eg `1.18.0-edge` 
Currently there is only `latest` and `edge` for the lightweight image, without versioning.

**Comment by ncarlier** [comment]
Last commit fix the lightweight Docker image publication.

**Comment by r3mi** [comment]
thanks
I am confused, I see there is a new `edge` image, but still no version ?
ie no `1.19.0-edge`

**Comment by ncarlier** [comment]
Hi, sorry I missed that last comment. `edge` tag is used without any version. It's the last commit of the main branch. It's considered a beta version, as it may contain bugs.

**Comment by r3mi** [comment]
ok, thanks, sorry I was confused
