### ISSUE TITLE
Change responce header: Content-Type

### ISSUE THREAD

**Issue by timonych** [ncarlier/webhookd#97]
Hello, @ncarlier 

Is it possible to change responce header Content-Type to application/json according to the request?
I haven't found this opportunity in docs or code.
I have also tryed to use header "Accept" in request, but nothing changes.

Everytime response header is `"Content-Type: text/plain; charset=utf-8"`

By the way, thx for this tool! :)

**Comment by ncarlier** [comment]
Hello, the latest commit should solve your problem. Webhookd will now take content negotiation into account.
