### ISSUE TITLE
err="bufio.Scanner: token too long

### ISSUE THREAD

**Issue by khfyf** [ncarlier/webhookd#98]
<img width="896" alt="webhookd" src="https://github.com/ncarlier/webhookd/assets/165630929/1e1fa4fb-513c-48d1-b156-3dfe5837a787">

thank you... for your hard work... to make this tool... it really helps me... in all my work

but.. I found a problem.. where when I.. tried to send data.. which was quite long.. it would get stuck.. and wouldn't issue a response.. it turned out that when I checked.. it got an error.. like the photo which I sent id**bufio.Scanner: token too long**

can you help me... to exceed this limit

**Comment by ncarlier** [comment]
Hello, the problem seems to be more related to the output of the script than to the input. It seems that you're printing very long text on a single line. Can you try splitting the output within your script?

**Comment by simoniz0r** [comment]
I've ran into this problem a few times also.  Splitting the output isn't always feasible to do.

**Comment by ncarlier** [comment]
Should be fixed.
